name: Deploy Docs
on:
  push:
    branches-ignore: [ gh-pages ]
    tags: '**'
  repository_dispatch:
    types: request-build-reference # legacy
  schedule:
  - cron: '0 10 * * *' # Once per day at 10am UTC
  workflow_dispatch:
permissions: read-all
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'spring-projects'
    env:
      DOCS_BUILD_BRANCH: docs-build
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: $DOCS_BUILD_BRANCH
        fetch-depth: 1
    - name: Dispatch (partial build)
      if: github.ref_type == 'branch'
      env:
        GH_TOKEN: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}
      run: gh workflow run deploy-docs.yml -r $DOCS_BUILD_BRANCH -f build-refname=${{ github.ref_name }}
    - name: Dispatch (full build)
      if: github.ref_type == 'tag'
      env:
        GH_TOKEN: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}
      run: gh workflow run deploy-docs.yml -r $DOCS_BUILD_BRANCH
